### ISSUE TITLE
k8s 1.22版本部署会出现证书签发问题，怎么解决呢 ERROR: After approving csr lxcfs-admission-webhook-svc.default, the signed certificate did not appear on the resource. Giving up after 10 attempts.

### ISSUE THREAD

**Issue by immortalZY** [denverdino/lxcfs-admission-webhook#24]

**Comment by solid-wang** [comment]
你需要修改deployment/webhook-create-signed-cert.sh中CertificateSigningRequest的部分
添加signerName、修改usages，如下：
`apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ${csrName}
spec:
  groups:
  - system:authenticated
  signerName: kubernetes.io/kube-apiserver-client
  request: $(cat ${tmpdir}/server.csr | base64 | tr -d '\n')
  usages:
  - client auth`

**Comment by solid-wang** [comment]
`apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ${csrName}
spec:
  groups:
  - system:authenticated
  signerName: kubernetes.io/kube-apiserver-client
  request: $(cat ${tmpdir}/server.csr | base64 | tr -d '\n')
  usages:
  - client auth`

**Comment by solid-wang** [comment]
你需要修改deployment/webhook-create-signed-cert.sh中的部分，如下：
```
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ${csrName}
spec:
  groups:
  - system:authenticated
  signerName: kubernetes.io/kube-apiserver-client
  request: $(cat ${tmpdir}/server.csr | base64 | tr -d '\n')
  usages:
  - client auth
```
